language: ruby

sudo: false

cache: bundler

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1

gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile

script:
  - bundle exec rake spec
  - bundle exec rake rdoc

matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/rails_4.0.gemfile
